config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root "home#show"
  get '/dashboard', to: 'dashboard#show'

  resources :workouts, only: [:show, :index]
  resources :user_races, only: [:new, :create, :edit, :update, :destroy]
end

app/models/formatter.rb
module Formatter
  
  def meter_to_mile
    (0.00062137119)
  end

  def meter_to_foot
    (3.28084)
  end

  def second_to_minute
    (0.01666667)
  end

  def mph_conversion
    (2.23694)
  end

  def time_converter(total_seconds)
    total_minutes = (total_seconds * second_to_minute)
    hours = (total_minutes / 60).to_i
    minutes = (total_minutes % 60).to_i
    time_formatter(hours, minutes)
  end

  def time_formatter(hours, minutes)
    hours == 0 ? "#{minutes} mins" : "#{hours}hr #{minutes}m"
  end

  def pace_converter(activity)
    minutes = (60.0 / average_speed(activity)).to_i
    seconds = ((60.0 / average_speed(activity) - minutes) * 60).to_i
    format_pace(minutes, seconds)
  end

  def format_pace(minutes, seconds)
    seconds < 10 ? "#{minutes}:0#{seconds}" : "#{minutes}:#{seconds}"
  end

  def format_date(activity)
    activity["start_date_local"].split("T").first[5..-1]
  end

  def format_time(activity)
    activity["start_date_local"].split("T").last.chop
  end

  def format_percentage(percent)
    if percent >= 1
      percentage = percent.round(2)
      "Your workout was #{percentage}x more difficult than"
    else
      percentage = (percent * 100).round(0)
      "Your workout was #{percentage}% as difficult as"
    end
  end

end

app/models/race.rb
class Race < ActiveRecord::Base
  validates :title, presence: true
  validates :title_id, presence: true
  validates :elevation_gain, presence: true
  validates :max_elevation, presence: true
  validates :distance, presence: true
end

app/models/running_tip.rb
class RunningTip < ActiveRecord::Base
  validates :tip, presence: true
end

app/models/scoring.rb
module Scoring
  
  def elevation_gain_factor
    gain_per_mile = (race.elevation_gain  / race.distance)     #Leadville 100 is the standard (18168ft/100miles)
    factor = gain_per_mile / 29.75     #85% of elevation score(max of 35%)   
  end

  def max_elevation_factor
    race.max_elevation / 5.25  #15% of elevation score
  end

  def possible_heartrate               
    190.0                       #Average 100% heartrate for 30 year old
  end

  def ideal_heartrate
    (possible_heartrate * 0.80).to_i       #Aerobic Zone is 70-80% of heartrate
  end

  def heartrate_factor                                    
    factor = (ideal_heartrate - 100) / 4.5                        #90% of heartrate score
  end

  def distance_factor
    factor = race.distance / 60.0
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_races
  has_one :user_statistic
  validates :provider, presence: true, acceptance: {accept: 'strava'}
  validates :user_id, presence: true
  validates :token, presence: true
  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  
  def self.find_or_create_by_auth(auth)
    user = User.find_or_create_by(provider: auth[:provider], user_id: auth[:uid])
    user_attributes(user, auth)
    user.save
    return user
  end

  def self.user_attributes(user, auth)
    user.token = auth[:credentials][:token]
    user.email = auth[:info][:email]
    user.name = auth[:info][:name]
    user.first_name = auth[:info][:first_name]
    user.last_name = auth[:info][:last_name]
    user.profile_picture = auth[:extra][:raw_info][:profile]
    user.city = auth[:extra][:raw_info][:city] || "Denver"
    user.state = auth[:extra][:raw_info][:state]
    user.sex = auth[:extra][:raw_info][:sex]
    user.athlete_type = auth[:extra][:raw_info][:athlete_type]
    user.weight = auth[:extra][:raw_info][:weight]
    user.shoes = auth[:extra][:raw_info][:shoes]
    user.follower_count = auth[:extra][:raw_info][:follower_count]
    user.friend_count = auth[:extra][:raw_info][:friend_count]
  end

end

app/models/user_race.rb
class UserRace < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

app/models/user_statistic.rb
class UserStatistic < ActiveRecord::Base
  belongs_to :user

  def self.user_statistic_attributes(current_user, service)
    user_statistic = find_or_create_by(user_id: current_user.id)
    
    user_statistic.update_attributes({
    user_id:           current_user.id,
    ytd_mileage:       service.distance("ytd"),
    ytd_sessions:      service.sessions("ytd"),
    ytd_duration:      service.duration("ytd"),
    ytd_elevation:     service.elevation_gain("ytd"),
    recent_mileage:    service.distance("recent"),
    recent_sessions:   service.sessions("recent"),
    recent_duration:   service.duration("recent"),
    recent_elevation:  service.elevation_gain("recent"),
    })
    return user_statistic
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, 
                :authorize!

  def current_user
    @current_user ||= User.find_by(user_id: session[:user_id]) if session[:user_id]
  end

  def authorize!
    redirect_to root_path, notice: "Please login to access your data" unless current_user
  end
end

app/controllers/concerns/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/dashboard_controller.rb
class DashboardController <ApplicationController
  before_action :authorize!
  
  def show
    @presenter = DashboardPresenter.new(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_by_auth(request.env['omniauth.auth'])
    if user 
      session[:user_id] = user.user_id
      redirect_to dashboard_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/user_races_controller.rb
class UserRacesController < ApplicationController
  before_action :authorize!
  
  def new
    @user_race = UserRace.new
  end

  def create
    @user_race = UserRace.new(user_race_params)
    @user_race.user_id = current_user.id
    
    @user_race.save
    redirect_to dashboard_path
  end

  def edit
    @user_race = UserRace.find(params[:id])
  end

  def update
    @user_race = UserRace.find(params[:id])
    @user_race.update(user_race_params)
    redirect_to dashboard_path
  end

  def destroy
    @user_race = UserRace.find(params[:id])
    @user_race.delete
    redirect_to dashboard_path
  end

  private

  def user_race_params
    params.require(:user_race).permit(:date, :title, :distance, :target_time, :location, :start_time)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authorize!

  def index
    @presenter = WorkoutsPresenter.new(current_user)
  end

  def show
    @presenter = WorkoutPresenter.new(current_user, params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/dashboard/_center_dashboard.html.erb
<% if @presenter.upcoming_races.count == 0 %>
  <%= render partial: "no_user_races" %>
<% else %>
  <%= render partial: "user_races_table" %>
<% end %> 

app/views/dashboard/_left_dashboard.html.erb
<% cache("ytd-stats-#{@presenter.current_user.id}", expires_in: (0.5).hours) do %>
  <div class="col s2 center" id="user-ytd">
    <br><br>
    <%= image_tag(current_user.profile_picture, class: "circle profile-pic") %>
    <br>
    <%= current_user.name %>

    <div class="card background-color">
      <div class="card-content">
        <span class="card-title">Year to Date</span>
        <hr>
        <p><i class="tiny material-icons">trending_flat</i> <%= number_with_delimiter(@presenter.stats.distance("ytd")) %> miles</p>
        <p><i class="tiny material-icons">query_builder</i> <%= @presenter.stats.sessions("ytd") %> sessions</p>
        <p><i class="tiny material-icons">query_builder</i> <%= number_with_delimiter(@presenter.stats.duration("ytd")) %></p>
        <p><i class="tiny material-icons">navigation</i> <%= number_with_delimiter(@presenter.stats.elevation_gain("ytd").to_i) %> ft gain</p>
      </div>
    </div>
<% end %> 

      <div class="card background-color">
        <div class="card-content">
          <span class="card-title">Running Tip</span>
          <hr>
          <p><%= @presenter.running_tip.tip %></p>
        </div>
      </div>
  </div>

app/views/dashboard/_no_user_races.erb
<% cache "no-races" do %>
  <div class="col s8 custom-padding">
    <h4 class="titillium center black-text grey-shadow">Upcoming Races & Goals
      <%= link_to new_user_race_path do %>
        <i class="small material-icons black-text">add</i>
      <% end %>
    </h4>

    <hr> 

    <h6 class="center">Keep your registered races and training goals in one place.</h6>
    
    <h5 class="titillium center black-text grey-shadow">Add a Race or Goal
      <%= link_to new_user_race_path do %>
        <i class="small material-icons black-text">add</i>
      <% end %>
    </h5>
    <div class="center">
      <%= link_to image_tag("BibRave.jpg", id: "bibrave", class: "center"), "http://www.bibrave.com/", :target => "_blank" %>
    </div>
    <%= render partial: "trails" %>
  </div>
<% end %>

app/views/dashboard/_right_dashboard.html.erb
<% cache("ytd-leaderboard", expires_in: (2).hours) do %>
  <div class="col s2 center" id="leaders-ytd">
    <br><br>
    <%= image_tag(@presenter.stat_leaders.first.user.profile_picture, class: "circle profile-pic") %>
    <br>
    <%= @presenter.stat_leaders.first.user.name %>
    <div class="card background-color">
      <div class="card-content">
        <span class="card-title">2016<br>Leaders</span>
        <hr>
        <% @presenter.stat_leaders.each do |leader| %>
        <p>
          <div style="font-size: 1.3em;"><%= leader.user.name %></div>
          <i class="tiny material-icons">trending_flat</i>
          <%= number_with_delimiter(leader.ytd_mileage) %> miles
          <br>
          <i class="tiny material-icons">query_builder</i>
          <%= number_with_delimiter(leader.ytd_sessions) %> sessions
          <br>
          <i class="tiny material-icons">query_builder</i>
          <%= number_with_delimiter(leader.ytd_duration) %>
          <br>
          <i class="tiny material-icons">navigation</i>
          <%= number_with_delimiter(leader.ytd_elevation) %> ft
        </p>
        <hr>
        <% end %>
      </div>
    </div> 
  </div>
<% end %>

app/views/dashboard/_trail_map.html.erb
<iframe
  width="400"
  height="340"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=<%= ENV['GOOGLE_MAPS'] %>
    &q=<%= @presenter.trail_service.latitude(trail) %>, <%= @presenter.trail_service.longitude(trail) %>
    &zoom=13
    &maptype=satellite" allowfullscreen>
</iframe>

app/views/dashboard/_trails.html.erb
<table class="bordered highlight centered responsive-table font-color font-outline" id="trail-index">
  <h4 class="titillium center black-text grey-shadow">Trails Near You
  <thead>
    <tr>
        <th data-field="Name">Name</th>
        <th data-field="Distance">Distance</th>
        <th data-field="Location">Location</th>
        <th data-field="Details">Details</th>
        <th data-field="Directions">Directions</th>
    </tr>
  </thead>

  <tbody>
    <% @presenter.trail_service.trails(current_user).each do |trail| %>
      <tr>
        <td><%= @presenter.trail_service.name(trail) %></td> 
        <td><%= @presenter.trail_service.distance(trail) %></td> 
        <td><%= @presenter.trail_service.city(trail) %>, <%= @presenter.trail_service.state(trail) %></td>
        <td>
          <ul class="collapsible" data-collapsible="accordion">
            <li>
              <div class="collapsible-header">Description</div>
              <div class="collapsible-body">
                <p><%= @presenter.trail_service.description(trail) %></p>
                <%= render partial: "trail_map", :locals => {:trail => trail}  %>
              </div>
            </li>
        </td>
        <td>
          <ul class="collapsible" data-collapsible="accordion">
            <li>
              <div class="collapsible-header">Directions</div>
              <div class="collapsible-body">
                <p><%= @presenter.trail_service.directions(trail) %></p>
              </div>
            </li>
          </ul>
        </td>
      </tr>
    <% end %> 
  </tbody>
</table>

app/views/dashboard/_user_races_table.html.erb
<% cache "user-races-#{@presenter.current_user}-#{current_user.user_races.maximum(:updated_at)}" do %>
  <div class="col s8 custom-padding" id="user-races">
    <table class="bordered highlight centered responsive-table font-color font-outline">
      <h4 class="titillium center black-text grey-shadow">Upcoming Races & Goals
        <%= link_to new_user_race_path do %>
          <i class="small material-icons black-text">add</i>
        <% end %> 
      <thead>
        <tr>
            <th data-field="Date">Date</th>
            <th data-field="Title">Title</th>
            <th data-field="Distance">Distance</th>
            <th data-field="Target">Target Time</th>
            <th data-field="Location">Location</th>
            <th data-field="Time">Start Time</th>
            <th data-field="Edit">Update</th>
        </tr>
      </thead>

      <tbody>
        <% @presenter.upcoming_races.each do |race| %>
          <tr>
            <td><%= race.date %></td> 
            <td><%= race.title %></td> 
            <td><%= race.distance %></td> 
            <td><%= race.target_time %></td>  
            <td><%= race.location %></td>
            <td><%= race.start_time %></td>
            <td><%= link_to("edit", edit_user_race_path(race.id), class: "edit-button") %>/<%=link_to("remove", user_race_path(race.id), method: :delete, class: "remove-button") %></td>
          </tr>
        <% end %> 
      </tbody>
    </table>
    <%= render partial: "trails" %>
  </div>
<% end %> 

app/views/dashboard/show.html.erb
<%= render partial: "/navbar/navbar" %> 
<div class="row background-color">
  <%= render partial: "left_dashboard" %>
  <%= render partial: "center_dashboard" %>
  <%= render partial: "right_dashboard" %>
</div>

app/views/home/show.html.erb
<% cache "home-page" do %> 
  <div class="anton">
    <div class="row center opaque white-text">
      <div class="col s12 m5 l5 offset-m6 offset-l6">
        <h1 class="titillium">PAINCAVER</h1>
        <%= link_to "Login with Strava", "/auth/strava", class: "btn btn-lg btn-default btn-home" %> 
        <p id='home-description'>Calculate your trail's difficulty rating using:</p>
        <div class="row center white-text">
          <div class="col s12 m4 l4">
            <i class="medium material-icons">navigation</i>
            <h5>elevation</h5>
          </div>
          <div class="col s12 m4 l4">
            <i class="medium material-icons">trending_up</i>
             <h5>heartrate</h5>
          </div>
          <div class="col s12 m4 l4">
            <i class="medium material-icons">query_builder</i>
             <h5>duration</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PAINCAVER</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
    <!-- Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Titillium Font -->
    <link href='https://fonts.googleapis.com/css?family=Titillium+Web:700italic' rel='stylesheet' type='text/css'>
    <%= favicon_link_tag 'paincaver-favicon.png' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <% flash.each do |type, msg| %>
        <div class="card">
          <p><center><%= content_tag :div, msg.html_safe %></center></p>
        </div>
      <% end %>
    </div>

    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
  </body>
</html>

app/views/navbar/_navbar.html.erb
<% cache "navabar" do %>
  <nav>
    <div class="nav-wrapper dirt-texture titillium">
      <a href="/dashboard" class="brand-logo">PAINCAVER</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "View Workouts", workouts_path %></li>
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      </ul>
    </div>
  </nav>
<% end %>

app/views/trails/display.html.erb
<!-- <%# cache "trail-#{@trail_service.name(@trail)}" do %>
  <table class="bordered highlight centered responsive-table font-color font-outline">
    <h4 class="titillium center black-text grey-shadow"><%= @trail_service.name(@trail) %> 
    <thead>
      <tr>
          <th data-field="Name">Name</th>
          <th data-field="Distance">Distance</th>
          <th data-field="Type">Type</th>
          <th data-field="City">City</th>
          <th data-field="State">State</th>
          <th data-field="Rating">Rating</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <%#= binding.pry %> 
        <td><%= @trail_service.name(@trail) %></td> 
        <td><%= @trail_service.distance(@trail) %></td> 
        <td><%= @trail_service.type(@trail) %></td> 
        <td><%= @trail_service.city(@trail) %></td> 
        <td><%= @trail_service.state(@trail) %></td> 
        <td><%= @trail_service.rating(@trail) %></td> 
        </td>
      </tr>
    </tbody>
  </table>
   
   <div class="card background-color">
     <div class="card-content">
      <span class="card-title">Description</span>
      <hr>
      <%= @trail_service.description(@trail) %> 
    </div>
   </div>


  <%= @trail_service.directions(@trail) %> 
<%# end %>  -->

app/views/user_races/_form.html.erb
<div class="anton">
  <div class="row white-text opaque">
    <div class="col s12 m4 offset-m7">
      <%= form_for @user_race do |f| %>
        
        <%= f.label :date %> 
        <%= f.date_field :date %>

        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :distance %>
        <%= f.number_field :distance, step: 0.1 %>

        <%= f.label :target_time %>
        <%= f.text_field :target_time %>

        <%= f.label :location %>
        <%= f.text_field :location %>

        <%= f.label :start_time %>
        <%= f.text_field :start_time %>

        <%= f.submit "#{type} Race" , class: "center btn" %>

      <% end %>
    </div>
  </div>
</div>

app/views/user_races/edit.html.erb
<%= render partial: "navbar/navbar" %>
<%= render partial: "form", :locals => {:type => "Update"}  %> 

app/views/user_races/new.html.erb
<%= render partial: "navbar/navbar" %>
<%= render partial: "form", :locals => {:type => "Add"} %> 

app/views/workouts/_index_center.html.erb
<% cache "user-activities-count-#{@presenter.count_activity_services}" do %>
  <div class="col s8 custom-padding" id="workouts-index">
    <h4 class="titillium center black-text grey-shadow">Workouts</h4>
    <table class="bordered highlight centered responsive-table font-color font-outline">
      <thead>
        <tr>
            <th data-field="Date">Date</th>
            <th data-field="Time">Start Time</th>
            <th data-field="Title">Title</th>
            <th data-field="Distance">Distance</th>
            <th data-field="Duration">Duration</th>
            <th data-field="Pace">Pace</th>
            <th data-field="Details">View Details</th>
        </tr>
      </thead>

      <tbody>
        <% @presenter.activities.each do |activity| %>
          <tr class="clickable-row" data-href="<%= workout_path(activity["id"]) %>">
            <td><%= @presenter.start_date(activity) %></td> 
            <td><%= @presenter.start_time(activity) %></td> 
            <td><%= @presenter.name(activity) %></td> 
            <td><%= @presenter.distance(activity) %> mi</td>  
            <td><%= @presenter.duration(activity) %></td>
            <td><%= @presenter.average_pace(activity) %></td>
            <td><%= link_to("details", workout_path(activity["id"]))%></td>
          </tr>
        <% end %> 
      </tbody>
    </table>
  </div>
<%end %> 

app/views/workouts/_index_left.html.erb
<% cache("monthly-stats-#{@presenter.current_user.id}", expires_in: (0.3).hours) do %>
  <div class="col s2 center" id="user-recent">
    <br><br>
    <%= image_tag(current_user.profile_picture, class: "circle profile-pic") %>
    <br>
    <%= current_user.name %>

      <div class="card background-color">
        <div class="card-content">
          <span class="card-title">Monthly Stats</span>
          <hr>
          <p><i class="tiny material-icons">trending_flat</i> <%= number_with_delimiter(@presenter.stats.distance("recent")) %> miles</p>
          <p><i class="tiny material-icons">query_builder</i> <%= @presenter.stats.sessions("recent") %> sessions</p>
          <p><i class="tiny material-icons">query_builder</i> <%= number_with_delimiter(@presenter.stats.duration("recent")) %></p>
          <p><i class="tiny material-icons">navigation</i> <%= number_with_delimiter(@presenter.stats.elevation_gain("recent").to_i) %> ft gain</p>
        </div>
      </div>

      <div class="card background-color">
        <div class="card-content">
          <span class="card-title">Running Tip</span>
          <hr>
          <p><%= @presenter.running_tip.tip %></p>
        </div>
      </div>
  </div>
<% end %> 

app/views/workouts/_index_right.erb
<div class="col s2 center">
  <br><br>
  <%= image_tag("anton-dashboard.jpg", class: "circle profile-pic") %>
  <br>
  <%= "Anton Krupicka" %>
  <div class="card background-color">
    <div class="card-content">
      <span class="card-title">Montly Stats</span>
      <hr>
      <p><i class="tiny material-icons">trending_flat</i>40.6<%#= number_with_delimiter(@stats.distance("ytd")) %> miles/week</p>
      <p><i class="tiny material-icons">query_builder</i>2 <%#= @stats.sessions("ytd") %> sessions/week</p>
      <p><i class="tiny material-icons">query_builder</i>7hr 35min <%#= number_with_delimiter(@stats.duration("ytd")) %>/week</p>
      <!-- <p><i class="tiny material-icons">navigation</i>89,757 <%#= number_with_delimiter(@stats.elevation_gain("ytd").to_i) %> ft gain</p> -->
      <hr>
      <ul class="collapsible" data-collapsible="accordion">
        <li>
          <div class="collapsible-header">Bio</div>
          <div class="collapsible-body"><p>Anton Krupicka is a Boulder based ultra-runner who has won the Leadville 100 twice. Minimalist.</p></div>
        </li>
      </ul>
    </div>
  </div>

  <div class="card background-color">
    <div class="card-content">
      <span class="card-title">Running Tip</span>
      <hr>
      <p><%= @running_tip.tip %></p>
    </div>
  </div>

</div>

app/views/workouts/_index_right.html.erb
<% cache("recent-leaderboard", expires_in: (0.5).hours) do %>
  <div class="col s2 center" id="leaderboard-recent">
    <br><br>
    <%= image_tag(@presenter.stat_leaders.first.user.profile_picture, class: "circle profile-pic") %>
    <br>
    <%= @presenter.stat_leaders.first.user.name %>
    <div class="card background-color">
      <div class="card-content">
        <span class="card-title">Mileage Leaders</span>
        <hr>
        <% @presenter.stat_leaders.each do |leader| %>
        <p>
          <div style="font-size: 1.3em;"><%= leader.user.name %></div>
          <i class="tiny material-icons">trending_flat</i>
          <%= number_with_delimiter(leader.recent_mileage) %> miles
          <br>
          <i class="tiny material-icons">query_builder</i>
          <%= number_with_delimiter(leader.recent_sessions) %> sessions
          <br>
          <i class="tiny material-icons">query_builder</i>
          <%= number_with_delimiter(leader.recent_duration) %>
          <br>
          <i class="tiny material-icons">navigation</i>
          <%= number_with_delimiter(leader.recent_elevation) %> ft
          <hr>
        </p>
        <% end %>
      </div>
    </div> 
  </div>
<% end %>

app/views/workouts/_show_left.html.erb
<div class="col s2 center">
  <br><br>
  <%= image_tag(current_user.profile_picture, class: "circle profile-pic") %>

  <div class="card background-color" id="race-selection">
    <div class="card-content">
    <h5>Course<br>Comparison</h5>
    <hr>
    <%= form_tag(workout_path(@presenter.activity), method: "get") do %>
      <div style="text-align:left">
        <%= radio_button_tag(:race, "leadville") %>
        <%= label_tag(:race_leadville, "Leadville 100") %>
        <%= radio_button_tag(:race, "boston") %>
        <%= label_tag(:race_boston, "Boston Marathon") %>
        <%= radio_button_tag(:race, "western") %>
        <%= label_tag(:race_western, "Western States") %>
        <%= radio_button_tag(:race, "badwater") %>
        <%= label_tag(:race_badwater, "Badwater 135") %>
        <%= radio_button_tag(:race, "hardrock") %>
        <%= label_tag(:race_hardrock, "Hardrock 100") %>
        <%= radio_button_tag(:race, "colfax") %>
        <%= label_tag(:race_colfax, "Colfax Half") %>
      </div>
      <br><br>
      <%= submit_tag("Calculate")%>
    <% end %>
    </div>
  </div>

  <div class="card background-color" id="race-details">
    <div class="card-content">
      <span class="card-title"><%= link_to(@presenter.race.title, @presenter.race.website) %> </span>
      <p><i class="tiny material-icons">query_builder</i> <%= number_with_delimiter(@presenter.race.distance) %> miles</p>
      <p><i class="tiny material-icons">query_builder</i> <%= number_with_delimiter(@presenter.race.course_record) %> CR</p>
      <p><i class="tiny material-icons">navigation</i> <%= number_with_delimiter(@presenter.race.elevation_gain.to_i) %> ft gain</p>
      <p><i class="tiny material-icons">navigation</i> <%= number_with_delimiter(@presenter.race.max_elevation.to_i) %> ft max</p>
    </div>
    <div class="card-action">
      <p style="text-decoration: underline"><%= @presenter.race.city %>, <%= @presenter.race.state %></p>
      <ul class="collapsible" data-collapsible="accordion">
        <li>
          <div class="collapsible-header">Race Description</div>
          <div class="collapsible-body"><p><%= @presenter.race.description %></p></div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/workouts/index.html.erb
<%= render partial: "/navbar/navbar" %> 
<div class="row background-color">
  <%= render partial: "index_left" %>
  <%= render partial: "index_center" %>
  <%= render partial: "index_right" %>
</div>

app/views/workouts/show.html.erb
<%= render partial: "/navbar/navbar" %> 
  
  <div class="row background-color">
    <%= render partial: "show_left" %> 
    
    <div class="col s10 custom-padding">
      <h3 class="titillium center"><%= @presenter.name(@presenter.activity) %></h3>
      <%= render partial: "workout_difficulty" %>
      <h4 class="titillium center">Snapshot</h4>

      <%= render partial: "workout_snapshot" %> 
      
      <%= render partial: "map" %>
    </div>
  </div>